remote_theme: jekyll/minima
mermaid: true

plugins:
  - jekyll-spaceship

collections:
  til:
    output: true
    permalink: /til/:name/

defaults:
  - scope:
      path: ""
      type: til
    values:
      layout: default
